import {
  // meta,
  // shopify,
  // starbucks,
  // tesla,
  api,
  app,
  blockchain,
  canva1,
  dapps,
  // caution,
  nft1,
  uiux,
  website,
  wordpress1,
  fx,
  nftimage,
  senzu,
  solanai,
  swap,
  swapspot,
  solanaag,
  ethag,
  defiag,
} from "../assets/images";
import {
  car,
  contact,
  css,
  Solidity,
  estate,
  express,
  git,
  github,
  html,
  javascript,
  linkedin,
  mongodb,
  motion,
  mui,
  nextjs,
  nodejs,
  pricewise,
  react,
  redux,
  sass,
  snapgram,
  summiz,
  tailwindcss,
  threads,
  typescript,
  python,
  aws,
  bootstrap,
  django,
  docker,
  ethereum,
  mysql,
  wordpress,
  photoshop,
  figma,
  metamask,
  solana,
  three,
  canva,
  vscode,
  nftmarketplace,
  defi,
  nft10,
  nft11,
  nft12,
  nft13,
  nft14,
  vscodez,
  htmlz,
  cssz,
  jsz,
  tailwindz,
  bootstrapz,
  reactz,
  nextz,
  mongodbz,
  sqlz,
  nodejsz,
  expressz,
  typescriptz,
  dockerj,
  gitz,
  githubz,
  solanaz,
  solidityz,
  remixz,
  rustz,
  hardhatz,
  anchorz,
  tonz,
  webflowz,
  figmaz,
  linux,
  pythonz,
  djz,
  unt,
} from "../assets/icons";

export const skills = [
  {
    imageUrl: linux,
    name: "LINUX",
    type: "Frontend",
  },
  {
    imageUrl: vscodez,
    name: "VSCODE",
    type: "Frontend",
  },

  {
    imageUrl: htmlz,
    name: "HTML",
    type: "Frontend",
  },
  {
    imageUrl: cssz,
    name: "CSS",
    type: "Frontend",
  },
  {
    imageUrl: jsz,
    name: "JavaScript",
    type: "Frontend",
  },
  {
    imageUrl: typescriptz,
    name: "TypeScript",
    type: "Frontend",
  },
  {
    imageUrl: tailwindz,
    name: "tailwind CSS",
    type: "Frontend",
  },
  {
    imageUrl: bootstrapz,
    name: "Bootstrap",
    type: "Frontend",
  },
  {
    imageUrl: reactz,
    name: "Ract.js",
    type: "Frontend",
  },
  {
    imageUrl: nextz,
    name: "Next.js",
    type: "Database",
  },
  {
    imageUrl: nodejsz,
    name: "Node.js",
    type: "Frontend",
  },
  {
    imageUrl: expressz,
    name: "Express",
    type: "Frontend",
  },
  {
    imageUrl: mongodbz,
    name: "MongoDB",
    type: "Frontend",
  },
  {
    imageUrl: sqlz,
    name: "SQL",
    type: "Frontend",
  },
  {
    imageUrl: aws,
    name: "AWS",
    type: "Frontend",
  },
  {
    imageUrl: pythonz,
    name: "Python",
    type: "Frontend",
  },

  {
    imageUrl: djz,
    name: "DJANGO",
    type: "Backend",
  },

  {
    imageUrl: dockerj,
    name: "DOCKER",
    type: "Backend",
  },
  {
    imageUrl: gitz,
    name: "GIT",
    type: "Database",
  },
  {
    imageUrl: githubz,
    name: "GitHub",
    type: "Database",
  },
  {
    imageUrl: unt,
    name: "Ethereum",
    type: "Version Control",
  },
  {
    imageUrl: solidityz,
    name: "Solidity",
    type: "Version Control",
  },

  {
    imageUrl: remixz,
    name: "Remix IDE",
    type: "Animation",
  },

  {
    imageUrl: hardhatz,
    name: "Hardhat",
    type: "State Management",
  },

  {
    imageUrl: solanaz,
    name: "Solana",
    type: "Frontend",
  },

  {
    imageUrl: rustz,
    name: "Rust",
    type: "Frontend",
  },
  {
    imageUrl: anchorz,
    name: "Anchor",
    type: "Frontend",
  },
  {
    imageUrl: tonz,
    name: "TON Blockchain",
    type: "Frontend",
  },
  {
    imageUrl: webflowz,
    name: "WEBFLOW",
    type: "Frontend",
  },
  {
    imageUrl: figmaz,
    name: "Figma",
    type: "Frontend",
  },
];

export const experiences = [
  {
    title: "Full-stack DApps Developer",
    company_name: "Blockchain",
    icon: dapps,
    iconBg: "#b7e4c7",
    date: "Jan 2020 - Present",
    points: [
      "Mastery in creating decentralized applications (DApps) from frontend interfaces to backend smart contract operations.",
      "Proficiency in building DApps on various blockchain networks such as Ethereum, Solana, and TON, ensuring flexibility and interoperability.",
      "Skilled in using languages and frameworks specific to different blockchains, including Solidity and Web3.js for Ethereum, Rust and Anchor for Solana, and TON-specific tools.",
      "Integrating decentralized finance (DeFi) protocols, ensuring 1st step security and transparent financial transactions within DApps.",
      "Architect and deploy scalable, dependable, and user-centric DApps based to different business specifications and user preferences.",
      "Frameworks such as Web3.js, ethers.js, Truffle, and Hardhat for Ethereum, and Anchor for Solana.",
    ],
  },
  {
    title: "Ethereum Developer",
    company_name: "Blockchain Innovations",
    icon: ethag,
    iconBg: "#338b99",
    date: "Feb 2019 - Present",
    points: [
      "Develop and deploy secure smart contracts on Ethereum Blockchain.",
      "Proficient with Solidity, Truffle, and Hardhat for robust contract creation.",
      "Use Web3.js and ethers.js for seamless frontend and Ethereum blockchain interactions.",
      "Implement DeFi solutions and NFT platforms, including lending, borrowing, staking, and digital asset creation.",
      "Optimize gas usage for cost-effective Ethereum smart contract deployment.",
      "Design and Develop advanced DApps, frontend applications with React and Next.js, enhancing user experience. Initial smart contract write & test using Remix or Foundry",
      "Deep understanding of Ethereum's ecosystem, including ERC standards and layer 2 solutions.",
    ],
  },

  {
    title: "Solana Developer",
    company_name: "Blockchain Innovations",
    icon: solanaag,
    iconBg: "#f5ecff",
    date: "Mar 2021 - Present",
    points: [
      "Build and deploy high-performance DApps on Solana.",
      "Proficient with Rust and Anchor for secure solana programs.",
      "Use Solana CLI for efficient blockchain development and deployment.",
      "Integrate Solana with React.js and Next.js front-end for user-friendly DApps. Initial programs write and test using solana playground",
      "Leverage Solana's high throughput for scalable applications.",
      "Implement token staking, creation, and DeFi functionalities on Solana.",
      "Deep understanding of Solana's ecosystem, including SPL and Serum DEX.",
    ],
  },
  {
    title: "Smart Contract Security and Auditor",
    company_name: "Blockchain Security Solutions",
    icon: dapps,
    iconBg: "#b7e4c7",
    date: "Jul 2020 - Present",
    points: [
      "Specialized in smart contract security and auditing.",
      "Smart contract invariants testing, fuzz testing and manual reviews using tools like Echidna and MythX.",
      "Stateless and stateful fuzzing tools such as Slither and Manticore.",
      "Develope and audit upgradeable smart contracts.",
      "Knowledgeable about common vulnerabilities like reentrancy and front-running.",
      "Secure coding methods to minimize attack surfaces.",
      "Conduct penetration testing to evaluate smart contract robustness.",
      "Ensure compliance with blockchain security standards.",
      "Security standards and best methods in the blockchain industry, ensuring compliance and adherence to guidelines.",
      "Have experience in securing high-value DApps and DeFi protocols, safeguarding user funds and assets.",
    ],
  },

  {
    title: "NFT Marketplace Developer",
    company_name: "Blockchain Innovators",
    icon: nft1,
    iconBg: "#ffe8ff",
    date: "Feb 2022 - Present",
    points: [
      "Develop NFT marketplaces across multiple blockchain networks.",
      "Expertise in Solidity, Rust, and blockchain languages for NFT creation and trading.",
      "Integrate Ethereum, Solana, and Binance Smart Chain for multi-chain NFT transactions.",
      "Proficient with ERC-721, ERC-1155, and other NFT standards.",
      "Use decentralized storage like IPFS and Arweave for secure NFT metadata.",
      "Design user-friendly interfaces with React.js, Next.js, and Tailwind CSS.",
      "Ensure robust blockchain security for NFT marketplaces.",
      "Deploy scalable NFT marketplaces with high transaction volume.",
    ],
  },
  {
    title: "DeFi Engineer",
    company_name: "Decentralized Finance Solutions",
    icon: defiag,
    iconBg: "#f3eed9",
    date: "Mar 2021 - Present",
    points: [
      "Develop secure and transparent decentralized finance (DeFi) applications.",
      "Solidity for smart contract development on Ethereum and other platforms.",
      "Integrate DeFi protocols like lending, borrowing, staking, and AMM.",
      "Decentralized exchanges (DEXs) and liquidity protocols.",
      "Use Web3.js, ethers.js, and Truffle for building and testing DApps.",
      "Strong knowledge of ERC-20 and ERC-721 token standards.",
      "Layer 2 scaling solutions and cross-chain bridges.",
      "Design user-friendly interfaces with React.js, Next.js, and TailwindCSS.",
      "Implement blockchain security best methodes to protect user funds.",
      "Deploy and manage DeFi applications on mainnet and testnet environments.",
    ],
  },

  {
    title: "MERN Stack Developer",
    company_name: "Tech Innovations Inc.",
    icon: website,
    iconBg: "#61dafb",
    date: "Mar 2018 - Present",
    points: [
      "Skilled in developing full-stack applications with the MERN stack (MongoDB, Express.js, React.js, Node.js).",
      "Design RESTful APIs with Express.js for efficient communication.",
      "Responsive front-end interfaces using React.js.",
      "MongoDB for optimized data management.",
      "Implementing user authentication using JWT and OAuth.",
      "State management using Redux and Context API.",
      "Handling real-time updates with WebSockets.",
      "Deploying MERN applications on AWS, Heroku, and DigitalOcean.",
      "Version control with Git.",
      "Agile development and CI/CD pipelines.",
    ],
  },

  {
    title: "API Developer",
    company_name: "Digital Solutions Co.",
    icon: api,
    iconBg: "#00ad84",
    date: "Jun 2017 - Present",
    points: [
      "Expert in designing & developing robust, scalable, and secure APIs.",
      "RESTful API design principles.",
      "GraphQL for flexible data querying.",
      "Backend API development using Node.js and Express.js.",
      "Strong understanding of HTTP protocols, status codes, and methods.",
      "Implementing authentication with OAuth 2.0, JWT, and API keys.",
      "Integrating third-party APIs and services.",
      "API documentation tools like Swagger and Postman.",
      "Conducting thorough API testing with Mocha, Chai, and Jest.",
      "API versioning strategies and deprecation policies.",
      "Deploying and managing APIs on AWS, Azure, and Google Cloud.",
    ],
  },
  {
    title: "Blockchain Network Developer",
    company_name: "Blockchain Innovations Inc.",
    icon: blockchain,
    iconBg: "#334a51",
    date: "May 2022 - Present",
    points: [
      "Developing and deploying blockchain networks like Bitcoin, Ethereum, and Dogecoin.",
      "Consensus algorithms (PoW, PoS, DPoS) for secure and efficient networks.",
      "P2P networking protocols for decentralized communication.",
      "Designing and maintaining blockchain data structures for integrity and immutability.",
      "Developing custom cryptographic solutions to enhance network security.",
      "Creating and managing secure blockchain wallets for digital assets.",
      "Strong understanding of smart contract platforms and implementation.",
      "Conducting thorough testing and validation of blockchain protocols.",
      "Developing tools for blockchain network monitoring and optimization.",
      "Collaborating with cross-functional teams for blockchain integration.",
      "Staying updated with emerging blockchain technologies and trends.",
    ],
  },
  {
    title: "Figma UI/UX Designer",
    company_name: "Creative Design Studio",
    icon: uiux,
    iconBg: "#d8ede7",
    date: "Apr 2021 - Present",
    points: [
      "Proficient in creating user-centric designs using Figma from concept to implementation.",
      "intuitive UIs for web and mobile applications.",
      "User research and usability testing to inform design decisions.",
      "Wireframes, prototypes, and high-fidelity mockups.",
      "Strong understanding of design principles, including typography, color theory, and visual hierarchy.",
      "Collaborated with developers and product managers to ensure design feasibility.",
      "Create and maintain design systems and style guides for consistency.",
      "Figma's collaborative features for feedback and iteration.",
      "Accessibility standards to create inclusive designs.",
      "Advanced design thinking methodologies to enhance user satisfaction.",
      "Continuous learning of new design trends, tools, and techniques.",
    ],
  },
];
